monolog:
    use_microseconds: true
    channels: [access, audit, security]

    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: debug

        access:
            type: stream
            path: "php://stdout"
            level: info
            channels: [access]

#        audit_json:
#            type: stream
#            path: '%kernel.logs_dir%/audit.jsonl'
#            level: info
#            channels: [audit]
#            formatter: monolog.formatter.json

        audit:
            type: stream
            path: "php://stdout"
            level: info
            channels: [audit]

        security:
            type: stream
            path: "php://stdout"
            level: notice
            channels: [security]
