monolog:
  channels: [access, audit, security]
  handlers:
    access_rotating:
      type: rotating_file
      path: '%kernel.logs_dir%/access.log'
      max_files: 365
      channels: [access]
    audit_db:
      type: stream
      path: '%kernel.logs_dir%/audit.jsonl'
      formatter: monolog.formatter.json
      channels: [audit]
    security_rotating:
      type: rotating_file
      path: '%kernel.logs_dir%/security.log'
      max_files: 365
      channels: [security]
  processors:
    - monolog.processor.web
    - monolog.processor.uid
    - monolog.processor.introspection
