framework:
    cache:
        app: cache.adapter.filesystem
    rate_limiter:
        limiters:
            login:
                policy: fixed_window
                limit: 5
                interval: '1 minute'
                cache_pool: cache.app
