services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $hexKey: '%env(APP_SECRETBOX_KEY)%'
            $childAppLoginUrl: '%env(string:MAIN_CHILD_APP_LOGIN_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Infrastructure\Provisioning\PostgresDbOrchestrator:
        arguments:
            $main: '@doctrine.dbal.default_connection'

    App\Logging\TenantContextProcessor:
        tags: [ { name: monolog.processor } ]

    App\Logging\AuditDbHandler: ~

    monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags: [ { name: monolog.processor } ]

    monolog.processor.uid:
        class: Monolog\Processor\UidProcessor
        tags: [ { name: monolog.processor } ]

    monolog.processor.introspection:
        class: Monolog\Processor\IntrospectionProcessor
        arguments: [ 'debug', [ ], 0 ]
        tags: [ { name: monolog.processor } ]
